4 CLEAR
4 EDIT
P ( BLOCK 5 - PROJECTILES )
U : ?A DUP @ 0 DO 2+ DUP ? LOOP ;
U 3 VARIABLE MISSILES 0 , 0 , 0 ,
U : FIREMISSILE 
U   MISSILES DUP @ 0 DO 
U     2+ DUP @ 0= IF 
U     LP @ SWAP ! LEAVE THEN
U   LOOP DROP ;
U 3 VARIABLE BOMBS 0 , 0 , 0 ,
U : DROPBOMBS 
U   BOMBS DUP @ 0 DO 
U     2+ DUP @ 0= IF 
U     EP @ SWAP ! LEAVE THEN
U   LOOP ;
