' LOAD ENEMY SPRITES
' LOAD LAUNCHER SPRITE
' DRAW BUNKERS
' GAME LOOP
' - DRAW ENEMIES
' - RANDOMLY DROP BOMBS
' - MOVE ENEMIES
' - DRAW BOMBS
' - DRAW LAUNCHER
' - GET INPUT
' -   - A - MOVE LEFT
' -   - D - MOVE RIGHT
' -   - S - FIRE MISSILE
' - DRAW MISSILES
' : FIRE MISSILE - INPUT SHIP X (SX), SHIP Y (SY), SHIP WIDTH (SW)
'  - LOOP THROUGH MISSILE ARRAY
'    - IF MX(M) = 0 THEM MX(M) = SX + SW/2: MY(M) = SY
'    - RETURN
' : DRAW MISSILES
' -   - LOOP M THROUGH MISSILE ARRAY
' -   - IF MX(M) > 0
'      - IF ENEMY HIT THEN DESTORY ENEMY: UPDATE SCORE:MX(M)=0
'      - IF BUNKER HIT THEN DAMAGE BUNKER: MX(M)=0
'      - MY(M) = MY(M) - 1
'      - IF MY(M) < 0 THEN MX(M)=0
'     RETURN
' - : DRAW ENEMIES STANDARD VERSION
'     P = P0 
' -   FOR R = 1 TO ER
'     SS = R
'     FOR C = 1 TO EC
'     DRAW SPRITE
'     P0 = P0 + EW
'     NEXT C
'     P0 = P0 + 32*EH+1
'     NEXT R


10
' LOAD ENEMY SPRITES

FOR I = 1 TO EC
SS = I
GOSUB READSPRITE
NEXT

' LOAD LAUNCHER SPRITE
SS = SS + 1
GOSUB READSPRITE

' LOAD BUNKER SRITE
SS = SS + 1
GOSUB READSPRITE

' DRAW BUNKERS
CLS 0
P = B0
FOR I = 1 TO 3
GOSUB DRAWSPRITE
P = P + BW ' ADD BUNKER WIDTH TO P
NEXT I

' GAME LOOP
GOSUB DRAWENEMIES
GOSUB DROPBOMBS
GOSUB DRAWBOMBS
GOSUB CHECKDIRECTION
E0 = E0 + ED
GOSUB DRAWLAUNCHER
' GET INPUT
IF PEEK(KL) = 247 AND L > L0 THEN L = L - 1
IF PEEK(KR) = 247 AND L < LN THEN L = L + 1
IF PEEK(KU) = 247 THEN GOSUB FIREMISSILE
GOSUB DRAWMISSILES
GOTO GAMELOOP

' DRAW MISSILES
FOR M = M0 TO MN
RESET(MX(M), MY(M)+1)
IF MX(M) = 0 THEN GOTO SKIPMISSILE
C = POINT(MX(M), MY(M))
IF C = C1 OR C = C2 THEN GOSUB ENEMYCOLLISION: RESET(MX(M),MY(M)) : GOTO SKIPMISSILE
IF C = BC THEN MX(M) = 0: GOTO SKIPMISSILE

SET(MX(M), MY(M), C4)
MY(M) = MY(M)-1
' SKIPMISSILE
NEXT
RETURN

' ENEMYCOLLISION
E = E0
FOR R = 1 TO ER
FOR C = 1 TO EC
X0 = FNX(E)
Y0 = FNY(E)
XN = X0 + EW
YN = Y0 + EH
IF NOT(MX(M) >= X0 AND MX(M) <= XN AND MY(M) >= Y0 AND MY(M) <= YN) THEN SKIPCOLLION
MX(M) = 0
EN(R,C)=0 : GOSUB DESTORYENEMY
SCORE = SCORE + 100
ET = ET - 1
IF ET = 0 THEN MG$ = "YOU WON": GOTO ENDGAME
' SKIPCOLLISION
NEXT
RETURN

' : FIRE MISSILE - INPUT SHIP X (SX), SHIP Y (SY), SHIP WIDTH (SW)
'  - LOOP THROUGH MISSILE ARRAY
'    - IF MX(M) = 0 THEM MX(M) = SX + SW/2: MY(M) = SY
'    - RETURN
' : DRAW MISSILES
' -   - LOOP M THROUGH MISSILE ARRAY
' -   - IF MX(M) > 0
'      - IF BUNKER HIT THEN DAMAGE BUNKER: MX(M)=0
'      - MY(M) = MY(M) - 1
'      - IF MY(M) < 0 THEN MX(M)=0
'     RETURN
' - : DRAW ENEMIES STANDARD VERSION
'     P = P0 
' -   FOR R = 1 TO ER
'     SS = R
'     FOR C = 1 TO EC
'     DRAW SPRITE
'     P0 = P0 + EW
'     NEXT C
'     P0 = P0 + 32*EH+1
'     NEXT R
